/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/kartu.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/kartu.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.card.geometry} material={materials.base} position={[-0.174, -0.031, 0.437]} />
      <mesh geometry={nodes.clip.geometry} material={materials.metal} position={[-0.174, -0.031, 0.437]} />
      <mesh geometry={nodes.clamp.geometry} material={materials.metal} position={[-0.174, -0.031, 0.437]} />
    </group>
  )
}

useGLTF.preload('/kartu.glb')
